# Assignment: Bank Account
# We are going to create a BankAccount class.
# This class will recreate some of the common account transactions that normally occur for a bank account
# such as displaying your account number, checking and savings amount, total amount.
# Of course, there are also methods to invoke such as depositing a check, checking your balance, withdrawing money

# BankAccount should have a method that returns a user's account number, account number should be generated by a private method, account number should be random
# BankAccount should have a method that returns the user's checking account balance
# BankAccount should have a method that returns the user's saving account balance
# BankAccount should allow a user to deposit money into either their checking or saving account
# BankAccount should allow a user to withdraw money from one of their accounts, return an error if there are insufficient funds
# BankAccount should allow the user to view the total amount of money they have at the bank
# BankAccount should track how many accounts the bank currently has
# Add an interest_rate attribute that is not accessible by the user. Set it to 0.01
# BankAccount should have a method called account_information that displays the users account number, total money, checking account balance, saving account balance and interest rate
# A user should not be able to set any attributes from the BankAccount class

require_relative 'bank_account'

x = BankAccount.new
x.deposit('checking', 7500)
x.deposit('saving', 101)

x.withdrawal('checking', 1111)
x.withdrawal('saving', 101)

puts x.total

puts x.account_information